### ISSUE TITLE
Permission to implement this theme for JetBrains IDE

### ISSUE THREAD

**Issue by mallowigi** [auroral-ui/aurora-future-vscode-theme#1]
Hi, 

I just discovered your theme and as a theme aficionado, I pretty much enjoy it. Can I implement it for JetBrains IDEs ? Thanks!

**Comment by bennyxguo** [comment]
@mallowigi  Yes feel free to do so, give me a link when you finish your theme, I will add it in my document, so for others that use JetBrains IDE can use it. :)
